apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: mw-pipeline
spec:
  params:
    - name: QUAY_REPO
      type: string
    - name: URL
      description: Repository URL to clone from
      type: string
    - name: REVISION
      description: 'Revision to checkout. (branch, tag, sha, ref, etc...)'
      type: string
      default: main
    - name: BUILD_SCRIPT
      description: 'The build script to embed with the Containerfile'
      type: string
      default: |
        date
    - name: RECIPE_IMAGE
      type: string
    - name: BUILD_TOOL
      type: string
    - name: BUILD_TOOL_VERSION
      type: string
    - name: JAVA_VERSION
      type: string
    - name: MVN_REPO_DEPLOY_URL
      description: Maven repository to deploy to
      type: string
      default: http://indyhost/ #TODO remove default
    - name: MVN_REPO_DEPENDENCIES_URL
      description: Maven repository to get dependencies from
      type: string
    - name: ACCESS_TOKEN
      type: string
    - name: BUILD_ID
      type: string
    - name: caTrustConfigMapName
      type: string
    - name: DOMAIN_PROXY_TARGET_ALLOWLIST
      type: string
      default: "localhost,gateway.indy.corp.stage.redhat.com,cdn-ubi.redhat.com,repo1.maven.org,repo.scala-sbt.org,scala.jfrog.io,repo.typesafe.com,jfrog-prod-usw2-shared-oregon-main.s3.amazonaws.com"
    - name: DOMAIN_PROXY_ENABLE_INTERNAL_PROXY
      type: string
      default: "true"
    - name: DOMAIN_PROXY_INTERNAL_PROXY_HOST
      type: string
      default: "localhost"
    - name: DOMAIN_PROXY_INTERNAL_PROXY_PORT
      type: string
      default: "8081"
    - name: DOMAIN_PROXY_INTERNAL_PROXY_USER
      type: string
      default: "$(params.BUILD_ID)+tracking"
    - name: DOMAIN_PROXY_INTERNAL_PROXY_PASSWORD
      type: string
      default: "$(params.ACCESS_TOKEN)"
    - name: DOMAIN_PROXY_INTERNAL_NON_PROXY_HOSTS
      type: string
      default: "localhost,gateway.indy.corp.stage.redhat.com"
    - name: ENABLE_INDY_PROXY
      type: string
    - name: INDY_PROXY_CLIENT_ID
      type: string
    - name: INDY_PROXY_CLIENT_CREDENTIAL
      type: string
    - name: NOTIFICATION_CONTEXT
      type: string
      default: ""
    - name: BIFROST_URL
      type: string
      default: ""
  workspaces:
    - name: source
      description: Workspace containing the source code
  tasks:
    - name: pnc-prebuild-git-clone-oci-ta
      params:
        - name: url
          value: $(params.URL)
        - name: revision
          value: $(params.REVISION)
        - name: verbose
          value: 'true'
        - name: ociStorage
          value: $(params.QUAY_REPO):trusted-source-$(context.pipelineRun.name)
        - name: RECIPE_IMAGE
          value: $(params.RECIPE_IMAGE)
        - name: BUILD_TOOL
          value: $(params.BUILD_TOOL)
        - name: BUILD_TOOL_VERSION
          value: $(params.BUILD_TOOL_VERSION)
        - name: JAVA_VERSION
          value: $(params.JAVA_VERSION)
        - name: BUILD_SCRIPT
          value: $(params.BUILD_SCRIPT)
      taskRef:
        resolver: bundles
        params:
          - name: name
            value: pnc-prebuild-git-clone-oci-ta
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-pnc-prebuild-git-clone-oci-ta:0.1
          - name: kind
            value: task

    - name: buildah-oci-ta
      runAfter:
        - pnc-prebuild-git-clone-oci-ta
      params:
        - name: SOURCE_ARTIFACT
          value: $(tasks.pnc-prebuild-git-clone-oci-ta.results.PRE_BUILD_IMAGE_DIGEST)
        - name: IMAGE # output image
          value: $(params.QUAY_REPO):build-$(context.pipelineRun.name)
        - name: DOCKERFILE # local path to the containerfile
          value: .jbs/Containerfile
        - name: caTrustConfigMapName
          value: $(params.caTrustConfigMapName)
        - name: ENABLE_INDY_PROXY
          value: $(params.ENABLE_INDY_PROXY)
        - name: INDY_PROXY_CLIENT_ID
          value: $(params.INDY_PROXY_CLIENT_ID)
        - name: INDY_PROXY_CLIENT_CREDENTIAL
          value: $(params.INDY_PROXY_CLIENT_CREDENTIAL)
        - name: BUILD_ARGS  #TODO this should be baked in the OCI source image only a ACCESS_TOKEN should be passed
          value:
            - PROXY_URL=$(params.MVN_REPO_DEPENDENCIES_URL)
            - BUILD_ID=$(params.BUILD_ID)
            - ACCESS_TOKEN=$(params.ACCESS_TOKEN)
        - name: BUILD_IMAGE
          value: quay.io/redhat-user-workloads/konflux-jbs-pnc-tenant/domain-proxy:latest
        - name: HERMETIC
          value: "true"
        - name: ENABLE_DOMAIN_PROXY
          value: "true"
        - name: DOMAIN_PROXY_TARGET_ALLOWLIST
          value: $(params.DOMAIN_PROXY_TARGET_ALLOWLIST)
        - name: DOMAIN_PROXY_ENABLE_INTERNAL_PROXY
          value: $(params.DOMAIN_PROXY_ENABLE_INTERNAL_PROXY)
        - name: DOMAIN_PROXY_INTERNAL_PROXY_HOST
          value: $(params.DOMAIN_PROXY_INTERNAL_PROXY_HOST)
        - name: DOMAIN_PROXY_INTERNAL_PROXY_PORT
          value: $(params.DOMAIN_PROXY_INTERNAL_PROXY_PORT)
        - name: DOMAIN_PROXY_INTERNAL_PROXY_USER
          value: $(params.DOMAIN_PROXY_INTERNAL_PROXY_USER)
        - name: DOMAIN_PROXY_INTERNAL_PROXY_PASSWORD
          value: $(params.DOMAIN_PROXY_INTERNAL_PROXY_PASSWORD)
        - name: DOMAIN_PROXY_INTERNAL_NON_PROXY_HOSTS
          value: $(params.DOMAIN_PROXY_INTERNAL_NON_PROXY_HOSTS)
      taskRef:
        #resolver: bundles
        #params:
        #  - name: name
        #    value: buildah-oci-ta
        #  - name: bundle
        #    value: quay.io/konflux-ci/tekton-catalog/task-buildah-oci-ta:0.2
        #  - name: kind
        #    value: task

        resolver: http
        params:
          - name: url
            value: https://raw.githubusercontent.com/redhat-appstudio/jvm-build-service/refs/heads/main/deploy/tasks/buildah-oci-ta.yaml

    - name: push-results
      runAfter:
        - buildah-oci-ta
      params:
        - name: IMAGE_URL
          value: $(tasks.buildah-oci-ta.results.IMAGE_URL)
        - name: IMAGE_DIGEST
          value: $(tasks.buildah-oci-ta.results.IMAGE_DIGEST)
        - name: MVN_REPO
          value: $(params.MVN_REPO_DEPLOY_URL)
        - name: ACCESS_TOKEN
          value: $(params.ACCESS_TOKEN)
        - name: BUILD_ID
          value: $(params.BUILD_ID)
        - name: BIFROST_URL
          value: $(params.BIFROST_URL)
      taskRef:
        resolver: http
        params:
          - name: url
            value: https://raw.githubusercontent.com/redhat-appstudio/jvm-build-service/refs/heads/main/deploy/tasks/push-results.yaml

  finally:
    - name: notification
      displayName: "Notify PNC driver"
      params:
        - name: ACCESS_TOKEN
          value: $(params.ACCESS_TOKEN)
        - name: NOTIFICATION_CONTEXT
          value: $(params.NOTIFICATION_CONTEXT)
        - name: STATUS
          value: $(tasks.status)
      taskSpec:
        params:
          - name: ACCESS_TOKEN
            description: Access token for OAuth.
            type: string
            default: ""
          - name: NOTIFICATION_CONTEXT
            description: Notification context
            type: string
          - name: STATUS
            description: Aggregate tasks status
            type: string
        steps:
          - name: notification
            image: quay.io/konflux-ci/pnc-konflux-tooling:latest@sha256:8c1c50b01c8dc5e3847f2ace4da8d28d255935b15c14d043bb2e819941697b29
            args:
              - notify
              - --context=$(params.NOTIFICATION_CONTEXT)
              - --status=$(params.STATUS)
              - --build-id=$(params.BUILD_ID)

